class MyException extends Exception {
 private int detail;
 MyException(int a) {
 detail = a;
 }
 public String toString() {
 return "MyException[" + detail + "]";
 }
}
class ExceptionHusnain {
 static void compute(int h) throws MyException {
 System.out.println("Called compute(" + h + ")");
 if(a > 10)
 throw new MyException(h);
 System.out.println("Normal exit");
 }
 public static void main(String args[]) {
 try {
 compute(1);
 compute(50);
 } catch (MyException h) {
 System.out.println("Caught " + h);
 }
 }
}
